spring:
  datasource:
    url: jdbc:h2:mem:emp_db;
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

# http://localhost:8080/h2-console
# http://localhost:8080/swagger-ui.html